### ISSUE TITLE
cluster size

### ISSUE THREAD

**Issue by claudiuskerth** [gui11aume/starcode#10]
I am struggling to make sense of the output from starcode. I have run _starcode_ on uniqued input reads (with `sort | uniq`), i. e. all input reads are different, but the output contains lines such as this one:

> TGCAGGTTTTGTTGG  1      TGCAGGTTTTGTTGG,TGCAGGTGCTGATAG

i. e. the cluster contains 2 different sequences, but the cluster is supposed to be composed of only 1 input sequence?! What does this number really say?

My command line options were:

> -d8 -t12 -s --print-clusters

many thanks for your help

claudius

**Comment by ezorita** [comment]
Hi Claudius,

Thank you for reporting. Definitely the output you got is not correct, the cluster size should be 2. However, when I try to reproduce the bug with a file containing only this sequences (TGCAGGTTTTGTTGG, TGCAGGTGCTGATAG) the output seems to be correct:

> TGCAGGTTTTGTTGG 2       TGCAGGTTTTGTTGG,TGCAGGTGCTGATAG

Could you please provide the following:
- Version of starcode you are using (branch and commit).
- An input file to reproduce the bug.
- Double check if the bug persists using -t1 to discard any concurrency-related problems.

Cheers,

Eduard

**Comment by claudiuskerth** [comment]
Hi Eduard,

I used `starcode`'s newest version from the `master` branch and the last `git` commit was:

> commit ea20fad1eb49a0dc289439f9d0984185f6e7ea44
Author: gui11aume <guillaume.filion@gmail.com>
Date:   Sat Feb 6 11:08:28 2016 +0100

    Corrected a bug introduced by previous bug correction.

I used a file of 134,492 reads, each 46 bp long:

[sort_uniqed_reads.txt](https://github.com/gui11aume/starcode/files/163111/sort_uniqed_reads.txt)

I have run these three command lines:

> starcode -d8 -t12 -s --print-clusters -i sort_uniqed_reads.txt -o starcode.out

> starcode -d8 -s --print-clusters -i sort_uniqed_reads.txt -o starcode_not_parallel.out

> starcode -d4 -t12 -s --print-clusters -i sort_uniqed_reads.txt -o starcode_maxDist_4.out

and all show clusters with more than one sequence in it but a "1" in the middle column.

**Comment by ezorita** [comment]
The issue seems to be solved now. Please pull the latest commit.
Thanks for reporting.

Eduard

**Comment by claudiuskerth** [comment]
Thanks for a very quick action on this issues!

claudius
