### ISSUE TITLE
edges of graph

### ISSUE THREAD

**Issue by claudiuskerth** [gui11aume/starcode#11]
Hi,

given that there are a multitude of different clustering algorithms out there, I think it would be great if you could provide an option to output the graph directly, e. g.

> seq_id_1   seq_id_2   distance

... so that the user can apply their the clustering algorithm of their choice.

many thanks

claudius

**Comment by ezorita** [comment]
Hi Claudius,

check out the repository, the branch [allpairs](https://github.com/gui11aume/starcode/tree/allpairs) is a version of starcode that performs no clustering and outputs all the sequence pairs within the specified distance. Let us know if this is what you need.

Eduard

**Comment by claudiuskerth** [comment]
Hi Eduard,

yes, that's exactly what I was thinking of :+1: 

Many thanks!

claudius
