### ISSUE TITLE
--non-redundant input

### ISSUE THREAD

**Issue by claudiuskerth** [gui11aume/starcode#16]
Hi Eduard,

I would like to use `starcode` with `--non-redundant` for removing PCR duplicates from a sequencing library. My read data files are compressed, of course. So I usually use process substitution like `--input1 <(zcat big_fastq.gz)` as input. However, with `--non-redundant` starcode derives the output file names from the input file names, so that I currently have to resort to named FIFO's, which is cumbersome since I have many input files that I want to make non-redundant. So, would it be possible for you to add two more flags to `starcode --non-redundant`, like `--output1` and `--output2`?

claudius

**Comment by claudiuskerth** [comment]
Hi Eduard,

I am wondering why I get a different read count in the output of `starcode` when clustering with and without the option `--non-redundant`.

Example input files:

[par_34-9.fq_1.gz](https://drive.google.com/open?id=0BzTtBMgLO1kedzJOMXpHbEhyRXc)
[par_34-9.fq_2.gz](https://drive.google.com/open?id=0BzTtBMgLO1keUkoyRDN3M2k5VkE)

I have run the following command lines on the input files:

>starcode -d 2 -t 12 -c -1 <(zcat data/par_34-9.fq_1.gz) -2 <(zcat data/par_34-9.fq_2.gz) | gzip > test_starcode/par_34-9.collapsed.gz

and 

>starcode -d 2 -t 12 -c --non-redundant -1 <(zcat data/par_34-9.fq_1.gz) -2 <(zcat data/par_34-9.fq_2.gz) --output1 >(gzip > test_starcode/par_34-9_dedup.fq_1.gz) --output2 >(gzip > test_starcode/par_34-9_dedup.fq_2.gz)

Counting the number of centroids in the output of the first command line:

>zcat  par_34-9.collapsed.gz | wc -l

I get:

179028

and counting the number of fastq records in the output from the second command line:

>zcat par_34-9_dedup.fq_1.gz | gawk '(NR-1)%4==0' | wc -l

I get:

204650

I would have thought these counts should be identical if the same clustering algorithm was used.

thank you so much for your help!

claudius

**Comment by ezorita** [comment]
Hi Claudius, 

thanks for reporting. They should indeed be identical. I will check what's going on.

Eduard

**Comment by ezorita** [comment]
Hi Claudius,

My apologies. Non-redundant output was meant to be only compatible with message passing clustering. When I implemented the connected components algorithm I forgot to flag them as incompatible, so starcode was automatically triggering MP when you used `--non-redundant` along with `-c`. 

Anyway, I have added a non-redundant output for both `spheres` and `connected components`. Please pull the last commit and let me know if you get the expected result.

Thanks

**Comment by claudiuskerth** [comment]
Hi Eduard,

I can confirm that the new starcode version (f1c3c71d00) now produces output with the same number of reads when using the input files and command lines above.

many thanks!

claudius
