### ISSUE TITLE
support compressed FASTQ files

### ISSUE THREAD

**Issue by Aargol** [gui11aume/starcode#25]
can u add support for accepting compressed FASTQ files such A1.fastq.gz or A1.fq.gz as inputs?

**Comment by ezorita** [comment]
You can use a named pipe as input to decompress on the fly. On a **bash-like** terminal use:

``
starcode -i <(zcat inputfile.fq.gz)
``

**Comment by Aargol** [comment]
Thanks :D

**Comment by Aargol** [comment]
Thanks 👍
