### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by raivivek** [gui11aume/starcode#35]
Wondering if authors could quickly create a new release with new changes so that downstream distribution channels such as Bioconda can utilize latest changes.

**Comment by ezorita** [comment]
Hi Vivek, thanks for the suggestion.

@gui11aume I agree we could jump version to 1.4, since 1.3 we just did introduce a major bug fix with sequence id in connected components.

Eduard

**Comment by raivivek** [comment]
Great, thanks! Looking forward to it.

**Comment by raivivek** [comment]
Hi @ezorita — gentle bump!

**Comment by ezorita** [comment]
Version 1.4 released
